// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi001.Data;

#nullable disable

namespace WebApi001.Migrations
{
    [DbContext(typeof(LibrarydbContext))]
    partial class LibrarydbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApi001.Model.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("AuthorId")
                        .HasName("PRIMARY");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("AvailableCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int(11)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("TotalCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("BookId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AuthorId" }, "FK_Books_Authors");

                    b.HasIndex(new[] { "CategoryId" }, "FK_Books_Categories");

                    b.HasIndex(new[] { "PublisherId" }, "FK_Books_Publishers");

                    b.HasIndex(new[] { "Isbn" }, "UQ_Books_ISBN")
                        .IsUnique();

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Bookissue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("MemberId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'Issued'");

                    b.HasKey("IssueId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "FK_BookIssues_Books");

                    b.HasIndex(new[] { "MemberId" }, "FK_BookIssues_Members");

                    b.ToTable("bookissues", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Bookreturn", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IssueId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ReturnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.HasKey("ReturnId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IssueId" }, "UQ_BookReturns_IssueId")
                        .IsUnique();

                    b.ToTable("bookreturns", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FineId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<decimal>("FineAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IssueId")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'Pending'");

                    b.HasKey("FineId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IssueId" }, "FK_Fines_BookIssues");

                    b.ToTable("fines", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("'Student'");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("curdate()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("MemberId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "UQ_Members_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "MembershipNumber" }, "UQ_Members_MembershipNumber")
                        .IsUnique();

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PublisherId")
                        .HasName("PRIMARY");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("WebApi001.Model.Book", b =>
                {
                    b.HasOne("WebApi001.Model.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Books_Authors");

                    b.HasOne("WebApi001.Model.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Books_Categories");

                    b.HasOne("WebApi001.Model.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK_Books_Publishers");

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("WebApi001.Model.Bookissue", b =>
                {
                    b.HasOne("WebApi001.Model.Book", "Book")
                        .WithMany("Bookissues")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_BookIssues_Books");

                    b.HasOne("WebApi001.Model.Member", "Member")
                        .WithMany("Bookissues")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_BookIssues_Members");

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WebApi001.Model.Bookreturn", b =>
                {
                    b.HasOne("WebApi001.Model.Bookissue", "Issue")
                        .WithOne("Bookreturn")
                        .HasForeignKey("WebApi001.Model.Bookreturn", "IssueId")
                        .IsRequired()
                        .HasConstraintName("FK_BookReturns_BookIssues");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("WebApi001.Model.Fine", b =>
                {
                    b.HasOne("WebApi001.Model.Bookissue", "Issue")
                        .WithMany("Fines")
                        .HasForeignKey("IssueId")
                        .IsRequired()
                        .HasConstraintName("FK_Fines_BookIssues");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("WebApi001.Model.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApi001.Model.Book", b =>
                {
                    b.Navigation("Bookissues");
                });

            modelBuilder.Entity("WebApi001.Model.Bookissue", b =>
                {
                    b.Navigation("Bookreturn");

                    b.Navigation("Fines");
                });

            modelBuilder.Entity("WebApi001.Model.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WebApi001.Model.Member", b =>
                {
                    b.Navigation("Bookissues");
                });

            modelBuilder.Entity("WebApi001.Model.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
